# Generated by Django 5.2.4 on 2025-07-30 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Gasolina, Eléctrico, Híbrido', max_length=50, unique=True)),
                ('descripcion', models.TextField(help_text='Una breve descripción sobre este tipo de vehículos.')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente a partir del nombre.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Mercedes-Benz Clase S', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción principal del vehículo.')),
                ('caracteristicas', models.CharField(help_text='Características breves separadas por comas. Ej: Asientos de cuero, climatización, etc.', max_length=255)),
                ('valor_slug', models.SlugField(help_text='Un identificador único para la URL y el formulario. Ej: mercedes-s', unique=True)),
                ('imagen', models.ImageField(help_text='Sube una imagen del vehículo.', upload_to='vehiculos/')),
                ('es_destacado', models.BooleanField(default=False, help_text="Marcar si este vehículo debe aparecer en la sección 'Destacados' de la página de inicio.")),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='DriveX.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
