# Generated by Django 5.2.4 on 2025-08-02 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveX', '0002_categoria_vehiculo_delete_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_servicio', models.DateField()),
                ('hora_servicio', models.TimeField()),
                ('duracion', models.CharField(max_length=50)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('direccion_recogida', models.CharField(max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('solicitudes_especiales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DriveX.vehiculo')),
            ],
        ),
    ]
