# Generated by Django 5.2.4 on 2025-08-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DriveX", "0003_reserva"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name_plural": "Categorías"},
        ),
    ]
