# Generated by Django 5.2.4 on 2025-08-08 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DriveX", "0004_alter_categoria_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la sucursal (ej. Quito Norte)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("ciudad", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("FINALIZADA", "Finalizada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                help_text="El estado actual de la reserva",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="vehiculo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas",
                to="DriveX.vehiculo",
            ),
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distancia",
                    models.PositiveIntegerField(
                        help_text="Distancia en kilómetros entre las dos sucursales."
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutas_llegada",
                        to="DriveX.sucursal",
                    ),
                ),
                (
                    "origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutas_salida",
                        to="DriveX.sucursal",
                    ),
                ),
            ],
            options={
                "unique_together": {("origen", "destino")},
            },
        ),
    ]
