# Generated by Django 5.2.4 on 2025-08-08 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DriveX", "0005_sucursal_reserva_estado_alter_reserva_usuario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="estado",
        ),
        migrations.AlterField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="vehiculo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="DriveX.vehiculo",
            ),
        ),
        migrations.DeleteModel(
            name="Ruta",
        ),
        migrations.DeleteModel(
            name="Sucursal",
        ),
    ]
