# Generated by Django 5.2.4 on 2025-08-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DriveX", "0007_sucursal_reserva_estado_alter_reserva_usuario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="categorias/"),
        ),
    ]
