# Generated by Django 5.2.4 on 2025-08-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DriveX", "0008_categoria_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Piloto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("disciplina", models.CharField(max_length=50)),
                ("edad", models.IntegerField()),
                ("altura_cm", models.IntegerField()),
                ("experiencia_años", models.IntegerField()),
                ("idiomas", models.CharField(max_length=100)),
                ("calificacion", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="pilotos/"),
                ),
            ],
        ),
    ]
